/* ═══════════════════════════════════════════════════════════════════
   HomeBrain — content.js
   ────────────────────────────────────────────────────────────────
   ARQUIVO PRINCIPAL DE CONTEÚDO DA PLATAFORMA.

   Como adicionar um produto novo:
     1. Copie qualquer objeto do array "products"
     2. Troque o "id" por algo único (sem espaços, use hífens)
     3. Preencha os campos (veja os comentários abaixo)
     4. Salve. O produto aparece automaticamente no site.

   Como adicionar uma trilha nova:
     1. Copie qualquer objeto do array "trails"
     2. Troque o "id" e preencha os campos
     3. No campo "productIds", coloque os IDs dos produtos da trilha

   Tipos de produto aceitos em "type":
     "ebook" | "audiobook" | "video" | "curso"

   Níveis de trilha aceitos em "level":
     "Iniciante" | "Intermediário" | "Avançado"

   Imagens: use URLs do Unsplash com o formato:
     "https://images.unsplash.com/photo-XXXXX?auto=format&fit=crop&w=600&q=80"
   Ou hospede suas próprias imagens na pasta /img/ e use "/img/nome.jpg"
═══════════════════════════════════════════════════════════════════ */

window.HB = window.HB || {};

window.HB.content = {

  // ── CONFIGURAÇÃO GERAL ─────────────────────────────────────────
  site: {
    name: "HomeBrain",
    tagline: "Conectando ideias, estudos e aprendizado.",
    stats: [
      { value: "+10 mil",       label: "alunos transformados" },
      { value: "4.500",         label: "produtos digitais"    },
      { value: "4.8/5",         label: "avaliação média"      },
      { value: "Acesso ilimitado", label: "com planos premium" },
    ],
  },

  // ── CATEGORIAS ─────────────────────────────────────────────────
  // Adicione quantas categorias quiser. O campo "id" é usado para filtrar.
  categories: [
    {
      id: "desenvolvimento-pessoal",
      name: "Desenvolvimento Pessoal",
      color: "#FF6B6B",
      image: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=400&q=80",
    },
    {
      id: "negocios-carreira",
      name: "Negócios e Carreira",
      color: "#4EC9C4",
      image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=400&q=80",
    },
    {
      id: "saude-bem-estar",
      name: "Saúde e Bem-estar",
      color: "#FF8E53",
      image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=400&q=80",
    },
    {
      id: "ciencia-tecnologia",
      name: "Ciência e Tecnologia",
      color: "#45B7D1",
      image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=400&q=80",
    },
    {
      id: "espiritualidade",
      name: "Espiritualidade",
      color: "#96CEB4",
      image: "https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=400&q=80",
    },
    {
      id: "artes-criatividade",
      name: "Artes e Criatividade",
      color: "#DDA0DD",
      image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=400&q=80",
    },
    {
      id: "historia-cultura",
      name: "História e Cultura",
      color: "#F7B731",
      image: "https://images.unsplash.com/photo-1461360228754-6e81c478b882?auto=format&fit=crop&w=400&q=80",
    },
    {
      id: "filosofia",
      name: "Filosofia",
      color: "#A29BFE",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=400&q=80",
    },
  ],

  // ── PRODUTOS ───────────────────────────────────────────────────
  // Campos obrigatórios: id, title, category, price, priceFormatted, image, description
  // Campos opcionais: author, type, fullDescription, rating, reviews, featured, tags, chapters
  products: [
    {
      id: "inteligencia-emocional",
      title: "Inteligência Emocional",
      author: "Daniel Goleman Jr.",
      category: "Desenvolvimento Pessoal",
      type: "ebook",
      price: 49.90,
      priceFormatted: "R$ 49,90",
      image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80",
      description: "Domine suas emoções e melhore suas relações",
      fullDescription: "Uma jornada profunda pelo universo das emoções humanas. Aprenda a identificar, compreender e gerenciar sentimentos para construir relacionamentos mais saudáveis e uma vida mais equilibrada com base em ciência e prática.",
      rating: 4,
      reviews: 324,
      featured: true,
      tags: ["emoções", "relacionamentos", "autoconhecimento"],
      chapters: [
        { title: "O que é inteligência emocional", duration: "18:20", text: "Inteligência emocional é a capacidade de reconhecer, compreender e gerenciar as próprias emoções e as emoções dos outros, impactando todas as áreas da vida." },
        { title: "Autoconhecimento emocional",      duration: "22:45", text: "O primeiro passo para desenvolver inteligência emocional é conhecer suas próprias emoções e como elas influenciam seu comportamento e decisões." },
        { title: "Autorregulação",                  duration: "20:10", text: "A capacidade de regular as próprias emoções é fundamental para tomar decisões racionais mesmo sob pressão e estresse." },
        { title: "Empatia e conexão humana",        duration: "19:35", text: "A empatia é a habilidade de se colocar no lugar do outro, compreendendo seus sentimentos e perspectivas sem julgamento." },
        { title: "Inteligência emocional no trabalho", duration: "24:00", text: "No ambiente profissional, a inteligência emocional é tão importante quanto as habilidades técnicas para o sucesso." },
      ],
    },
    {
      id: "produtividade-maxima",
      title: "Produtividade Máxima",
      author: "James Clear",
      category: "Desenvolvimento Pessoal",
      type: "ebook",
      price: 39.90,
      priceFormatted: "R$ 39,90",
      image: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&w=600&q=80",
      description: "Técnicas práticas para fazer mais em menos tempo",
      fullDescription: "Descubra os sistemas e hábitos que os profissionais de alto desempenho usam para maximizar resultados, eliminar distrações e alcançar seus objetivos com consistência e sem esgotamento.",
      rating: 4,
      reviews: 289,
      featured: true,
      tags: ["produtividade", "hábitos", "foco", "gestão do tempo"],
      chapters: [
        { title: "O mito da multitarefa",          duration: "16:30", text: "A ciência comprova: fazer várias coisas ao mesmo tempo reduz a qualidade e aumenta o tempo gasto em cada tarefa. O foco singular é o segredo." },
        { title: "O método time blocking",          duration: "20:15", text: "Reserve blocos fixos de tempo para atividades específicas e proteja esses blocos como compromissos inegociáveis na sua agenda." },
        { title: "Eliminando distrações digitais",  duration: "18:40", text: "Smartphone, e-mail e redes sociais são os maiores ladrões de atenção do século XXI. Aprenda a recuperar o controle da sua atenção." },
        { title: "O poder dos pequenos hábitos",   duration: "22:00", text: "Hábitos de 1% de melhoria diária resultam em resultados 37 vezes melhores ao fim de um ano." },
      ],
    },
    {
      id: "neurociencia-aprendizado",
      title: "Neurociência do Aprendizado",
      author: "Dr. Carlos Menezes",
      category: "Ciência e Tecnologia",
      type: "audiobook",
      price: 59.90,
      priceFormatted: "R$ 59,90",
      image: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?auto=format&fit=crop&w=600&q=80",
      description: "Como o cérebro aprende e como usar isso a seu favor",
      fullDescription: "Descubra como o cérebro humano cria memórias, consolida aprendizados e supera bloqueios cognitivos. Com base nas mais recentes pesquisas em neurociência, este livro oferece estratégias práticas para aprender qualquer coisa de forma mais rápida, duradoura e eficiente.",
      rating: 5,
      reviews: 412,
      featured: true,
      tags: ["neurociência", "memória", "aprendizado", "cérebro"],
      chapters: [
        { title: "Como o cérebro aprende",          duration: "24:38", text: "O cérebro humano possui cerca de 86 bilhões de neurônios conectados em redes complexas. A aprendizagem ocorre quando essas conexões são fortalecidas por repetição e emoção." },
        { title: "Memória de curto e longo prazo",  duration: "18:45", text: "A memória não é um arquivo estático. Cada vez que você acessa uma memória, ela é reconstruída pelo cérebro." },
        { title: "Plasticidade neuronal",           duration: "22:10", text: "O cérebro adulto continua criando novas conexões neurais. A neuroplasticidade significa que a capacidade de aprender não diminui com a idade." },
        { title: "A técnica da repetição espaçada", duration: "20:55", text: "Revisar conteúdo em intervalos crescentes é a técnica mais eficaz para retenção de longo prazo, segundo dezenas de estudos." },
        { title: "Emoção e aprendizagem",           duration: "16:30", text: "A amígdala, centro emocional do cérebro, fortalece as memórias associadas a emoções." },
        { title: "Sono e consolidação de memórias", duration: "19:20", text: "Durante o sono REM, o hipocampo faz o replay dos aprendizados do dia para o córtex." },
        { title: "Foco profundo e Flow",            duration: "25:10", text: "O estado de flow é a condição ideal para o aprendizado de alta qualidade." },
        { title: "Técnicas práticas para estudar",  duration: "21:42", text: "Repetição espaçada, autoexplicação, prática de recordação e simulação são as estratégias mais comprovadas pela ciência." },
      ],
    },
    {
      id: "mentalidade-sucesso",
      title: "Mentalidade e Sucesso",
      author: "Carol S. Dweck",
      category: "Desenvolvimento Pessoal",
      type: "ebook",
      price: 44.90,
      priceFormatted: "R$ 44,90",
      image: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=600&q=80",
      description: "Desenvolva uma mentalidade forte e vencedora",
      fullDescription: "A diferença entre pessoas que prosperam e as que estagnam está na mentalidade. Este livro revela como desenvolver uma mentalidade de crescimento que transforma desafios em oportunidades de aprendizado.",
      rating: 4,
      reviews: 351,
      featured: true,
      tags: ["mentalidade", "sucesso", "crescimento", "resiliência"],
      chapters: [
        { title: "Mentalidade fixa vs. crescimento", duration: "20:00", text: "Pessoas com mentalidade fixa acreditam que talentos são inatos. Pessoas com mentalidade de crescimento acreditam que habilidades são desenvolvidas pelo esforço." },
        { title: "O poder do 'ainda'",              duration: "15:30", text: "Substituir 'não consigo' por 'ainda não consigo' muda completamente a perspectiva sobre dificuldades e fracassos." },
        { title: "Transformando críticas em crescimento", duration: "18:00", text: "Pessoas com mentalidade de crescimento encaram críticas como feedback valioso, não como ataques pessoais." },
      ],
    },
    {
      id: "meditacao-guiada",
      title: "Meditação Guiada",
      author: "Jon Kabat-Zinn",
      category: "Saúde e Bem-estar",
      type: "audiobook",
      price: 29.90,
      priceFormatted: "R$ 29,90",
      image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=600&q=80",
      description: "Reduza o estresse e encontre equilíbrio",
      fullDescription: "Uma coleção de meditações guiadas para reduzir ansiedade, melhorar o foco e cultivar presença plena no dia a dia. Ideal para iniciantes e praticantes experientes que buscam equilíbrio.",
      rating: 4,
      reviews: 271,
      featured: true,
      tags: ["meditação", "mindfulness", "ansiedade", "bem-estar"],
      chapters: [
        { title: "Introdução ao mindfulness",  duration: "12:00", text: "Mindfulness é a prática de prestar atenção intencionalmente ao momento presente, sem julgamentos ou distrações." },
        { title: "Respiração consciente",      duration: "15:20", text: "A respiração é a âncora do mindfulness. Focar na respiração acalma o sistema nervoso e traz o foco ao presente." },
        { title: "Varredura corporal",         duration: "20:10", text: "A varredura corporal é uma prática que envolve prestar atenção sistemática a cada parte do corpo." },
        { title: "Meditação da bondade amorosa", duration: "18:00", text: "A prática de cultivar sentimentos de amor e bondade por si mesmo e pelos outros reduz ansiedade e melhora bem-estar." },
      ],
    },
    {
      id: "financas-pessoais",
      title: "Finanças Pessoais",
      author: "Gustavo Cerbasi",
      category: "Negócios e Carreira",
      type: "ebook",
      price: 39.90,
      priceFormatted: "R$ 39,90",
      image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=600&q=80",
      description: "Organize suas finanças e construa riqueza",
      fullDescription: "Da gestão do orçamento ao investimento inteligente, este guia completo oferece estratégias práticas para sair das dívidas e construir patrimônio de forma consistente e sustentável.",
      rating: 4,
      reviews: 198,
      featured: true,
      tags: ["finanças", "investimentos", "dívidas", "patrimônio"],
      chapters: [
        { title: "Diagnóstico financeiro",    duration: "18:00", text: "O primeiro passo para organizar as finanças é entender onde você está: quanto ganha, quanto gasta e para onde vai seu dinheiro." },
        { title: "Criando um orçamento real", duration: "22:30", text: "Um orçamento eficiente não é uma prisão, mas um mapa que te guia para seus objetivos financeiros de longo prazo." },
        { title: "Reserva de emergência",     duration: "16:45", text: "Antes de investir, é essencial ter uma reserva de emergência equivalente a 6 meses de gastos mensais." },
        { title: "Primeiros investimentos",   duration: "28:00", text: "Tesouro Direto, fundos de índice e ações: como começar a investir com qualquer valor de forma segura." },
      ],
    },
    {
      id: "historia-brasil",
      title: "História do Brasil",
      author: "Boris Fausto",
      category: "História e Cultura",
      type: "ebook",
      price: 34.90,
      priceFormatted: "R$ 34,90",
      image: "https://images.unsplash.com/photo-1461360228754-6e81c478b882?auto=format&fit=crop&w=600&q=80",
      description: "Uma jornada pela história do nosso país",
      fullDescription: "Do descobrimento à república, uma análise completa e acessível da história brasileira, com contexto cultural, político e social de cada período histórico.",
      rating: 4,
      reviews: 187,
      featured: false,
      tags: ["história", "brasil", "cultura", "política"],
      chapters: [
        { title: "O Brasil colonial",     duration: "30:00", text: "O período colonial brasileiro durou de 1500 a 1822 e foi marcado pela exploração de recursos naturais e pela escravidão." },
        { title: "O Império",             duration: "25:00", text: "O período imperial (1822-1889) foi marcado pela independência e pela construção de uma identidade nacional brasileira." },
        { title: "A República Velha",     duration: "22:00", text: "A Primeira República (1889-1930) foi dominada pela política do café com leite entre São Paulo e Minas Gerais." },
      ],
    },
    {
      id: "fisica-quantica",
      title: "Física Quântica Descomplicada",
      author: "Carlo Rovelli",
      category: "Ciência e Tecnologia",
      type: "ebook",
      price: 54.90,
      priceFormatted: "R$ 54,90",
      image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=600&q=80",
      description: "O universo quântico explicado para todos",
      fullDescription: "Uma viagem fascinante ao mundo subatômico, onde as regras da física clássica não se aplicam e a realidade é muito mais estranha e bela do que imaginamos.",
      rating: 5,
      reviews: 143,
      featured: false,
      tags: ["física", "quantum", "ciência", "universo"],
      chapters: [
        { title: "O que é a física quântica",  duration: "20:00", text: "A física quântica descreve o comportamento da matéria e da energia em escalas muito pequenas." },
        { title: "Superposição e colapso",     duration: "18:30", text: "Uma partícula quântica pode existir em múltiplos estados simultaneamente até ser observada." },
      ],
    },
    {
      id: "lideranca-criativa",
      title: "Liderança Criativa",
      author: "Simon Sinek",
      category: "Negócios e Carreira",
      type: "curso",
      price: 47.90,
      priceFormatted: "R$ 47,90",
      image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=600&q=80",
      description: "Lidere equipes e construa culturas de alto impacto",
      fullDescription: "Aprenda os princípios de liderança que inspiram equipes a dar o melhor de si, construir confiança e alcançar resultados extraordinários com propósito e clareza.",
      rating: 4,
      reviews: 211,
      featured: false,
      tags: ["liderança", "gestão", "equipe", "cultura"],
      chapters: [
        { title: "Comece pelo porquê",   duration: "22:00", text: "Os grandes líderes começam com o propósito — o porquê — antes de pensar no como e no quê." },
        { title: "Construindo confiança", duration: "19:15", text: "Confiança é a base de qualquer equipe de alto desempenho, construída com consistência e vulnerabilidade." },
      ],
    },
    {
      id: "nutricao-longevidade",
      title: "Nutrição e Longevidade",
      author: "Valter Longo",
      category: "Saúde e Bem-estar",
      type: "ebook",
      price: 37.90,
      priceFormatted: "R$ 37,90",
      image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=600&q=80",
      description: "Coma bem, viva mais e com mais qualidade",
      fullDescription: "Baseado em décadas de pesquisa sobre longevidade e alimentação, este guia oferece estratégias nutricionais práticas para uma vida mais longa e saudável.",
      rating: 4,
      reviews: 156,
      featured: false,
      tags: ["nutrição", "saúde", "longevidade", "alimentação"],
      chapters: [
        { title: "A dieta da longevidade",  duration: "24:00", text: "Populações com maior longevidade do mundo compartilham princípios alimentares comuns: pouca proteína animal, muitas plantas." },
      ],
    },
    {
      id: "arte-digital",
      title: "Pintura Digital",
      author: "Loish",
      category: "Artes e Criatividade",
      type: "video",
      price: 44.90,
      priceFormatted: "R$ 44,90",
      image: "https://images.unsplash.com/photo-1542185400-f1c993ecbea2?auto=format&fit=crop&w=600&q=80",
      description: "Crie arte digital profissional do zero",
      fullDescription: "Um curso completo de pintura digital para iniciantes e intermediários. Aprenda técnicas de composição, luz, sombra e cor para criar ilustrações profissionais.",
      rating: 5,
      reviews: 89,
      featured: false,
      tags: ["arte", "design", "digital", "ilustração"],
      chapters: [
        { title: "Ferramentas e software", duration: "15:00", text: "Conheça as principais ferramentas para pintura digital: Photoshop, Procreate, Clip Studio Paint." },
        { title: "Luz e sombra",           duration: "28:00", text: "Compreender luz e sombra é fundamental para criar ilustrações com volume e profundidade." },
      ],
    },
    {
      id: "meditacao-budista",
      title: "Meditação Budista",
      author: "Thich Nhat Hanh",
      category: "Espiritualidade",
      type: "audiobook",
      price: 32.90,
      priceFormatted: "R$ 32,90",
      image: "https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=600&q=80",
      description: "A sabedoria budista para o mundo moderno",
      fullDescription: "Uma introdução profunda e acessível à meditação budista e seus fundamentos filosóficos, com práticas guiadas para cultivar paz interior, compaixão e presença plena.",
      rating: 5,
      reviews: 94,
      featured: false,
      tags: ["budismo", "meditação", "espiritualidade", "paz"],
      chapters: [
        { title: "Os fundamentos do budismo",  duration: "20:00", text: "O budismo é um caminho de prática e desenvolvimento da mente e do coração, não uma religião de adoração." },
        { title: "As Quatro Nobres Verdades",  duration: "18:30", text: "As Quatro Nobres Verdades são o núcleo do ensinamento de Buda sobre o sofrimento e sua cessação." },
      ],
    },
  ],

  // ── TRILHAS ────────────────────────────────────────────────────
  // Adicione trilhas aqui. No campo "productIds", liste os IDs dos
  // produtos que fazem parte da trilha (devem existir acima em products).
  trails: [
    {
      id: "foco-disciplina",
      title: "Foco e Disciplina",
      description: "Desenvolva foco profundo e hábitos de alta performance para conquistar seus objetivos com consistência.",
      category: "Mente",
      level: "Iniciante",
      image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=600&q=80",
      lessons: 12,
      completed: 6,
      productIds: ["produtividade-maxima", "inteligencia-emocional"],
    },
    {
      id: "aprender-ensinar",
      title: "Aprender para Ensinar",
      description: "Como absorver e transmitir conhecimento de forma eficaz e transformadora para qualquer audiência.",
      category: "Educação",
      level: "Intermediário",
      image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=600&q=80",
      lessons: 15,
      completed: 8,
      productIds: ["neurociencia-aprendizado", "inteligencia-emocional"],
    },
    {
      id: "comunicacao-eficaz",
      title: "Comunicação Eficaz",
      description: "Fale com clareza, ouça com presença e construa conexões reais em qualquer contexto profissional ou pessoal.",
      category: "Carreira",
      level: "Iniciante",
      image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=600&q=80",
      lessons: 10,
      completed: 5,
      productIds: ["inteligencia-emocional", "lideranca-criativa"],
    },
    {
      id: "lideranca-gestao",
      title: "Liderança e Gestão",
      description: "Lidere equipes, gerencie projetos e crie culturas de alto desempenho com autenticidade e propósito.",
      category: "Carreira",
      level: "Avançado",
      image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=600&q=80",
      lessons: 14,
      completed: 7,
      productIds: ["lideranca-criativa", "mentalidade-sucesso"],
    },
    {
      id: "saude-mental",
      title: "Saúde Mental e Equilíbrio",
      description: "Ferramentas práticas para gerenciar ansiedade, estresse e bem-estar emocional no cotidiano.",
      category: "Saúde",
      level: "Iniciante",
      image: "https://images.unsplash.com/photo-1531747118685-ca8fa6e08806?auto=format&fit=crop&w=600&q=80",
      lessons: 9,
      completed: 0,
      productIds: ["meditacao-guiada", "meditacao-budista"],
    },
    {
      id: "financas-do-zero",
      title: "Finanças do Zero",
      description: "Da dívida ao patrimônio: aprenda a gerenciar e investir dinheiro com inteligência e consistência.",
      category: "Finanças",
      level: "Iniciante",
      image: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&w=600&q=80",
      lessons: 16,
      completed: 4,
      productIds: ["financas-pessoais"],
    },
    {
      id: "ciencia-sono",
      title: "Ciência do Sono",
      description: "Durma melhor, acorde disposto e maximize seu desempenho cognitivo e físico através do sono de qualidade.",
      category: "Saúde",
      level: "Iniciante",
      image: "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=600&q=80",
      lessons: 8,
      completed: 8,
      productIds: ["neurociencia-aprendizado", "meditacao-guiada"],
    },
    {
      id: "criatividade-inovacao",
      title: "Criatividade e Inovação",
      description: "Técnicas de pensamento criativo para resolver problemas complexos e criar soluções únicas e impactantes.",
      category: "Criatividade",
      level: "Intermediário",
      image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=600&q=80",
      lessons: 11,
      completed: 3,
      productIds: ["arte-digital", "mentalidade-sucesso"],
    },
    {
      id: "estoicismo",
      title: "Estoicismo Prático",
      description: "Filosofia aplicada ao dia a dia: resiliência, foco e serenidade em qualquer situação da vida moderna.",
      category: "Filosofia",
      level: "Intermediário",
      image: "https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=600&q=80",
      lessons: 10,
      completed: 0,
      productIds: ["meditacao-budista"],
    },
  ],

}; // fim window.HB.content
