/* ═══════════════════════════════════════════════════════════════════
   HomeBrain — content.js
   ────────────────────────────────────────────────────────────────
   ARQUIVO PRINCIPAL DE CONTEÚDO DA PLATAFORMA.

   Como adicionar um produto novo:
     1. Copie qualquer objeto do array "products"
     2. Troque o "id" por algo único (sem espaços, use hífens)
     3. Preencha os campos (veja os comentários abaixo)
     4. Salve. O produto aparece automaticamente no site.

   Como adicionar uma trilha nova:
     1. Copie qualquer objeto do array "trails"
     2. Troque o "id" e preencha os campos
     3. No campo "productIds", coloque os IDs dos produtos da trilha

   Tipos de produto aceitos em "type":
     "ebook" | "audiobook" | "video" | "curso"

   Níveis de trilha aceitos em "level":
     "Iniciante" | "Intermediário" | "Avançado"

   Imagens: use URLs do Unsplash com o formato:
     "https://images.unsplash.com/photo-XXXXX?auto=format&fit=crop&w=600&q=80"
   Ou hospede suas próprias imagens na pasta /img/ e use "/img/nome.jpg"
═══════════════════════════════════════════════════════════════════ */

window.HB = window.HB || {};

window.HB.content = {

  // ── CONFIGURAÇÃO GERAL ─────────────────────────────────────────
  site: {
    name: "HomeBrain",
    tagline: "Conectando ideias, estudos e aprendizado.",
    stats: [
      { value: "+10 mil",       label: "alunos transformados" },
      { value: "4.500",         label: "produtos digitais"    },
      { value: "4.8/5",         label: "avaliação média"      },
      { value: "Acesso ilimitado", label: "com planos premium" },
    ],
  },

  // ── CATEGORIAS ─────────────────────────────────────────────────
  // Adicione quantas categorias quiser. O campo "id" é usado para filtrar.
  categories: [
    {
      id: "desenvolvimento-pessoal",
      name: "Desenvolvimento Pessoal",
      color: "#FF6B6B",
      image: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=400&q=80",
    },
    {
      id: "negocios-carreira",
      name: "Negócios e Carreira",
      color: "#4EC9C4",
      image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=400&q=80",
    },
    {
      id: "saude-bem-estar",
      name: "Saúde e Bem-estar",
      color: "#FF8E53",
      image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=400&q=80",
    },
    {
      id: "ciencia-tecnologia",
      name: "Ciência e Tecnologia",
      color: "#45B7D1",
      image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=400&q=80",
    },
    {
      id: "espiritualidade",
      name: "Espiritualidade",
      color: "#96CEB4",
      image: "https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=400&q=80",
    },
    {
      id: "artes-criatividade",
      name: "Artes e Criatividade",
      color: "#DDA0DD",
      image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=400&q=80",
    },
    {
      id: "historia-cultura",
      name: "História e Cultura",
      color: "#F7B731",
      image: "https://images.unsplash.com/photo-1461360228754-6e81c478b882?auto=format&fit=crop&w=400&q=80",
    },
    {
      id: "filosofia",
      name: "Filosofia",
      color: "#A29BFE",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=400&q=80",
    },
    {
      id: "programacao",
      name: "Programação",
      color: "#00D9FF",
      image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=400&q=80",
    },
  ],

  // ── PRODUTOS ───────────────────────────────────────────────────
  // Campos obrigatórios: id, title, category, price, priceFormatted, image, description
  // Campos opcionais: author, type, fullDescription, rating, reviews, featured, tags, chapters
  products: [
    {
      id: "inteligencia-emocional",
      title: "Inteligência Emocional",
      author: "Daniel Goleman Jr.",
      category: "Desenvolvimento Pessoal",
      type: "ebook",
      price: 49.90,
      priceFormatted: "R$ 49,90",
      image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80",
      description: "Domine suas emoções e melhore suas relações",
      fullDescription: "Uma jornada profunda pelo universo das emoções humanas. Aprenda a identificar, compreender e gerenciar sentimentos para construir relacionamentos mais saudáveis e uma vida mais equilibrada com base em ciência e prática.",
      rating: 4,
      reviews: 324,
      featured: true,
      tags: ["emoções", "relacionamentos", "autoconhecimento"],
      chapters: [
        { title: "O que é inteligência emocional", duration: "18:20", text: "Inteligência emocional é a capacidade de reconhecer, compreender e gerenciar as próprias emoções e as emoções dos outros, impactando todas as áreas da vida." },
        { title: "Autoconhecimento emocional",      duration: "22:45", text: "O primeiro passo para desenvolver inteligência emocional é conhecer suas próprias emoções e como elas influenciam seu comportamento e decisões." },
        { title: "Autorregulação",                  duration: "20:10", text: "A capacidade de regular as próprias emoções é fundamental para tomar decisões racionais mesmo sob pressão e estresse." },
        { title: "Empatia e conexão humana",        duration: "19:35", text: "A empatia é a habilidade de se colocar no lugar do outro, compreendendo seus sentimentos e perspectivas sem julgamento." },
        { title: "Inteligência emocional no trabalho", duration: "24:00", text: "No ambiente profissional, a inteligência emocional é tão importante quanto as habilidades técnicas para o sucesso." },
      ],
    },
    {
      id: "produtividade-maxima",
      title: "Produtividade Máxima",
      author: "James Clear",
      category: "Desenvolvimento Pessoal",
      type: "ebook",
      price: 39.90,
      priceFormatted: "R$ 39,90",
      image: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&w=600&q=80",
      description: "Técnicas práticas para fazer mais em menos tempo",
      fullDescription: "Descubra os sistemas e hábitos que os profissionais de alto desempenho usam para maximizar resultados, eliminar distrações e alcançar seus objetivos com consistência e sem esgotamento.",
      rating: 4,
      reviews: 289,
      featured: true,
      tags: ["produtividade", "hábitos", "foco", "gestão do tempo"],
      chapters: [
        { title: "O mito da multitarefa",          duration: "16:30", text: "A ciência comprova: fazer várias coisas ao mesmo tempo reduz a qualidade e aumenta o tempo gasto em cada tarefa. O foco singular é o segredo." },
        { title: "O método time blocking",          duration: "20:15", text: "Reserve blocos fixos de tempo para atividades específicas e proteja esses blocos como compromissos inegociáveis na sua agenda." },
        { title: "Eliminando distrações digitais",  duration: "18:40", text: "Smartphone, e-mail e redes sociais são os maiores ladrões de atenção do século XXI. Aprenda a recuperar o controle da sua atenção." },
        { title: "O poder dos pequenos hábitos",   duration: "22:00", text: "Hábitos de 1% de melhoria diária resultam em resultados 37 vezes melhores ao fim de um ano." },
      ],
    },
    {
      id: "neurociencia-aprendizado",
      title: "Neurociência do Aprendizado",
      author: "Dr. Carlos Menezes",
      category: "Ciência e Tecnologia",
      type: "audiobook",
      price: 59.90,
      priceFormatted: "R$ 59,90",
      image: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?auto=format&fit=crop&w=600&q=80",
      description: "Como o cérebro aprende e como usar isso a seu favor",
      fullDescription: "Descubra como o cérebro humano cria memórias, consolida aprendizados e supera bloqueios cognitivos. Com base nas mais recentes pesquisas em neurociência, este livro oferece estratégias práticas para aprender qualquer coisa de forma mais rápida, duradoura e eficiente.",
      rating: 5,
      reviews: 412,
      featured: true,
      tags: ["neurociência", "memória", "aprendizado", "cérebro"],
      chapters: [
        { title: "Como o cérebro aprende",          duration: "24:38", text: "O cérebro humano possui cerca de 86 bilhões de neurônios conectados em redes complexas. A aprendizagem ocorre quando essas conexões são fortalecidas por repetição e emoção." },
        { title: "Memória de curto e longo prazo",  duration: "18:45", text: "A memória não é um arquivo estático. Cada vez que você acessa uma memória, ela é reconstruída pelo cérebro." },
        { title: "Plasticidade neuronal",           duration: "22:10", text: "O cérebro adulto continua criando novas conexões neurais. A neuroplasticidade significa que a capacidade de aprender não diminui com a idade." },
        { title: "A técnica da repetição espaçada", duration: "20:55", text: "Revisar conteúdo em intervalos crescentes é a técnica mais eficaz para retenção de longo prazo, segundo dezenas de estudos." },
        { title: "Emoção e aprendizagem",           duration: "16:30", text: "A amígdala, centro emocional do cérebro, fortalece as memórias associadas a emoções." },
        { title: "Sono e consolidação de memórias", duration: "19:20", text: "Durante o sono REM, o hipocampo faz o replay dos aprendizados do dia para o córtex." },
        { title: "Foco profundo e Flow",            duration: "25:10", text: "O estado de flow é a condição ideal para o aprendizado de alta qualidade." },
        { title: "Técnicas práticas para estudar",  duration: "21:42", text: "Repetição espaçada, autoexplicação, prática de recordação e simulação são as estratégias mais comprovadas pela ciência." },
      ],
    },
    {
      id: "mentalidade-sucesso",
      title: "Mentalidade e Sucesso",
      author: "Carol S. Dweck",
      category: "Desenvolvimento Pessoal",
      type: "ebook",
      price: 44.90,
      priceFormatted: "R$ 44,90",
      image: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=600&q=80",
      description: "Desenvolva uma mentalidade forte e vencedora",
      fullDescription: "A diferença entre pessoas que prosperam e as que estagnam está na mentalidade. Este livro revela como desenvolver uma mentalidade de crescimento que transforma desafios em oportunidades de aprendizado.",
      rating: 4,
      reviews: 351,
      featured: true,
      tags: ["mentalidade", "sucesso", "crescimento", "resiliência"],
      chapters: [
        { title: "Mentalidade fixa vs. crescimento", duration: "20:00", text: "Pessoas com mentalidade fixa acreditam que talentos são inatos. Pessoas com mentalidade de crescimento acreditam que habilidades são desenvolvidas pelo esforço." },
        { title: "O poder do 'ainda'",              duration: "15:30", text: "Substituir 'não consigo' por 'ainda não consigo' muda completamente a perspectiva sobre dificuldades e fracassos." },
        { title: "Transformando críticas em crescimento", duration: "18:00", text: "Pessoas com mentalidade de crescimento encaram críticas como feedback valioso, não como ataques pessoais." },
      ],
    },
    {
      id: "meditacao-guiada",
      title: "Meditação Guiada",
      author: "Jon Kabat-Zinn",
      category: "Saúde e Bem-estar",
      type: "audiobook",
      price: 29.90,
      priceFormatted: "R$ 29,90",
      image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=600&q=80",
      description: "Reduza o estresse e encontre equilíbrio",
      fullDescription: "Uma coleção de meditações guiadas para reduzir ansiedade, melhorar o foco e cultivar presença plena no dia a dia. Ideal para iniciantes e praticantes experientes que buscam equilíbrio.",
      rating: 4,
      reviews: 271,
      featured: true,
      tags: ["meditação", "mindfulness", "ansiedade", "bem-estar"],
      chapters: [
        { title: "Introdução ao mindfulness",  duration: "12:00", text: "Mindfulness é a prática de prestar atenção intencionalmente ao momento presente, sem julgamentos ou distrações." },
        { title: "Respiração consciente",      duration: "15:20", text: "A respiração é a âncora do mindfulness. Focar na respiração acalma o sistema nervoso e traz o foco ao presente." },
        { title: "Varredura corporal",         duration: "20:10", text: "A varredura corporal é uma prática que envolve prestar atenção sistemática a cada parte do corpo." },
        { title: "Meditação da bondade amorosa", duration: "18:00", text: "A prática de cultivar sentimentos de amor e bondade por si mesmo e pelos outros reduz ansiedade e melhora bem-estar." },
      ],
    },
    {
      id: "financas-pessoais",
      title: "Finanças Pessoais",
      author: "Gustavo Cerbasi",
      category: "Negócios e Carreira",
      type: "ebook",
      price: 39.90,
      priceFormatted: "R$ 39,90",
      image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=600&q=80",
      description: "Organize suas finanças e construa riqueza",
      fullDescription: "Da gestão do orçamento ao investimento inteligente, este guia completo oferece estratégias práticas para sair das dívidas e construir patrimônio de forma consistente e sustentável.",
      rating: 4,
      reviews: 198,
      featured: true,
      tags: ["finanças", "investimentos", "dívidas", "patrimônio"],
      chapters: [
        { title: "Diagnóstico financeiro",    duration: "18:00", text: "O primeiro passo para organizar as finanças é entender onde você está: quanto ganha, quanto gasta e para onde vai seu dinheiro." },
        { title: "Criando um orçamento real", duration: "22:30", text: "Um orçamento eficiente não é uma prisão, mas um mapa que te guia para seus objetivos financeiros de longo prazo." },
        { title: "Reserva de emergência",     duration: "16:45", text: "Antes de investir, é essencial ter uma reserva de emergência equivalente a 6 meses de gastos mensais." },
        { title: "Primeiros investimentos",   duration: "28:00", text: "Tesouro Direto, fundos de índice e ações: como começar a investir com qualquer valor de forma segura." },
      ],
    },
    {
      id: "historia-brasil",
      title: "História do Brasil",
      author: "Boris Fausto",
      category: "História e Cultura",
      type: "ebook",
      price: 34.90,
      priceFormatted: "R$ 34,90",
      image: "https://images.unsplash.com/photo-1461360228754-6e81c478b882?auto=format&fit=crop&w=600&q=80",
      description: "Uma jornada pela história do nosso país",
      fullDescription: "Do descobrimento à república, uma análise completa e acessível da história brasileira, com contexto cultural, político e social de cada período histórico.",
      rating: 4,
      reviews: 187,
      featured: false,
      tags: ["história", "brasil", "cultura", "política"],
      chapters: [
        { title: "O Brasil colonial",     duration: "30:00", text: "O período colonial brasileiro durou de 1500 a 1822 e foi marcado pela exploração de recursos naturais e pela escravidão." },
        { title: "O Império",             duration: "25:00", text: "O período imperial (1822-1889) foi marcado pela independência e pela construção de uma identidade nacional brasileira." },
        { title: "A República Velha",     duration: "22:00", text: "A Primeira República (1889-1930) foi dominada pela política do café com leite entre São Paulo e Minas Gerais." },
      ],
    },
    {
      id: "fisica-quantica",
      title: "Física Quântica Descomplicada",
      author: "Carlo Rovelli",
      category: "Ciência e Tecnologia",
      type: "ebook",
      price: 54.90,
      priceFormatted: "R$ 54,90",
      image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=600&q=80",
      description: "O universo quântico explicado para todos",
      fullDescription: "Uma viagem fascinante ao mundo subatômico, onde as regras da física clássica não se aplicam e a realidade é muito mais estranha e bela do que imaginamos.",
      rating: 5,
      reviews: 143,
      featured: false,
      tags: ["física", "quantum", "ciência", "universo"],
      chapters: [
        { title: "O que é a física quântica",  duration: "20:00", text: "A física quântica descreve o comportamento da matéria e da energia em escalas muito pequenas." },
        { title: "Superposição e colapso",     duration: "18:30", text: "Uma partícula quântica pode existir em múltiplos estados simultaneamente até ser observada." },
      ],
    },
    {
      id: "lideranca-criativa",
      title: "Liderança Criativa",
      author: "Simon Sinek",
      category: "Negócios e Carreira",
      type: "curso",
      price: 47.90,
      priceFormatted: "R$ 47,90",
      image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=600&q=80",
      description: "Lidere equipes e construa culturas de alto impacto",
      fullDescription: "Aprenda os princípios de liderança que inspiram equipes a dar o melhor de si, construir confiança e alcançar resultados extraordinários com propósito e clareza.",
      rating: 4,
      reviews: 211,
      featured: false,
      tags: ["liderança", "gestão", "equipe", "cultura"],
      chapters: [
        { title: "Comece pelo porquê",   duration: "22:00", text: "Os grandes líderes começam com o propósito — o porquê — antes de pensar no como e no quê." },
        { title: "Construindo confiança", duration: "19:15", text: "Confiança é a base de qualquer equipe de alto desempenho, construída com consistência e vulnerabilidade." },
      ],
    },
    {
      id: "nutricao-longevidade",
      title: "Nutrição e Longevidade",
      author: "Valter Longo",
      category: "Saúde e Bem-estar",
      type: "ebook",
      price: 37.90,
      priceFormatted: "R$ 37,90",
      image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=600&q=80",
      description: "Coma bem, viva mais e com mais qualidade",
      fullDescription: "Baseado em décadas de pesquisa sobre longevidade e alimentação, este guia oferece estratégias nutricionais práticas para uma vida mais longa e saudável.",
      rating: 4,
      reviews: 156,
      featured: false,
      tags: ["nutrição", "saúde", "longevidade", "alimentação"],
      chapters: [
        { title: "A dieta da longevidade",  duration: "24:00", text: "Populações com maior longevidade do mundo compartilham princípios alimentares comuns: pouca proteína animal, muitas plantas." },
      ],
    },
    {
      id: "arte-digital",
      title: "Pintura Digital",
      author: "Loish",
      category: "Artes e Criatividade",
      type: "video",
      price: 44.90,
      priceFormatted: "R$ 44,90",
      image: "https://images.unsplash.com/photo-1542185400-f1c993ecbea2?auto=format&fit=crop&w=600&q=80",
      description: "Crie arte digital profissional do zero",
      fullDescription: "Um curso completo de pintura digital para iniciantes e intermediários. Aprenda técnicas de composição, luz, sombra e cor para criar ilustrações profissionais.",
      rating: 5,
      reviews: 89,
      featured: false,
      tags: ["arte", "design", "digital", "ilustração"],
      chapters: [
        { title: "Ferramentas e software", duration: "15:00", text: "Conheça as principais ferramentas para pintura digital: Photoshop, Procreate, Clip Studio Paint." },
        { title: "Luz e sombra",           duration: "28:00", text: "Compreender luz e sombra é fundamental para criar ilustrações com volume e profundidade." },
      ],
    },
    {
      id: "meditacao-budista",
      title: "Meditação Budista",
      author: "Thich Nhat Hanh",
      category: "Espiritualidade",
      type: "audiobook",
      price: 32.90,
      priceFormatted: "R$ 32,90",
      image: "https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=600&q=80",
      description: "A sabedoria budista para o mundo moderno",
      fullDescription: "Uma introdução profunda e acessível à meditação budista e seus fundamentos filosóficos, com práticas guiadas para cultivar paz interior, compaixão e presença plena.",
      rating: 5,
      reviews: 94,
      featured: false,
      tags: ["budismo", "meditação", "espiritualidade", "paz"],
      chapters: [
        { title: "Os fundamentos do budismo",  duration: "20:00", text: "O budismo é um caminho de prática e desenvolvimento da mente e do coração, não uma religião de adoração." },
        { title: "As Quatro Nobres Verdades",  duration: "18:30", text: "As Quatro Nobres Verdades são o núcleo do ensinamento de Buda sobre o sofrimento e sua cessação." },
      ],
    },
    {
      id: "python-fundamentos",
      title: "Python: Fundamentos Essenciais",
      author: "Mentor Python",
      category: "Programação",
      type: "audiobook",
      price: 0,
      priceFormatted: "GRÁTIS",
      image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=600&q=80",
      description: "Aprenda os conceitos básicos de Python: variáveis, tipos de dados, operadores e primeira linha de código.",
      fullDescription: "Neste módulo você vai dominar os fundamentos de Python. Começamos do zero, entendendo como o Python funciona, como executar código e os conceitos básicos de programação. Você vai escrever seu primeiro programa, entender variáveis, tipos de dados (int, float, string, bool) e operadores matemáticos. Ideal para quem nunca programou!",
      rating: 5,
      reviews: 342,
      featured: true,
      tags: ["python", "iniciante", "fundamentos", "variáveis"],
      chapters: [
        { title: "Bem-vindo ao Python", duration: "12:34", text: "Introdução ao curso e ao mundo da programação..." },
        { title: "Instalando Python e IDE", duration: "18:45", text: "Como instalar Python, VSCode e primeiras configurações..." },
        { title: "Seu Primeiro Programa", duration: "15:20", text: "Escreva print('Olá Mundo!') e entenda como funciona..." },
        { title: "Variáveis e Tipos de Dados", duration: "22:10", text: "int, float, string, bool. Como Python gerencia tipos..." },
        { title: "Operadores Matemáticos", duration: "19:55", text: "+, -, *, /, %, **, //. Ordem das operações..." },
        { title: "Exercícios Práticos", duration: "25:30", text: "Resolva 5 exercícios do zero ao avançado..." }
      ]
    },
    {
      id: "python-controle-fluxo",
      title: "Python: Controle de Fluxo (if, else, loops)",
      author: "Mentor Python",
      category: "Programação",
      type: "audiobook",
      price: 49.90,
      priceFormatted: "R$ 49,90",
      image: "https://images.unsplash.com/photo-1633356270529-e4f1e24ebed8?auto=format&fit=crop&w=600&q=80",
      description: "Domine if/else, while, for loops e lógica de decisão. Prepare-se para o Projeto 1: Jogo de Adivinhação.",
      fullDescription: "Aqui você aprende a controlar o fluxo de seu programa. Entenda como usar if, elif, else para tomar decisões. Domine loops while e for para repetir código. Pratique lógica de programação com exercícios reais. Ao final, você estará pronto para criar o Projeto 1: um jogo completo de adivinhação.",
      rating: 5,
      reviews: 298,
      featured: true,
      tags: ["python", "iniciante", "if-else", "loops", "lógica"],
      chapters: [
        { title: "Condicionais: if e else", duration: "20:12", text: "Tomando decisões no código..." },
        { title: "Comparadores e Operadores Lógicos", duration: "18:45", text: "==, !=, <, >, and, or, not..." },
        { title: "elif: Múltiplas Condições", duration: "16:30", text: "Como lidar com várias possibilidades..." },
        { title: "Loop while: Repetição com Condição", duration: "21:00", text: "Repetindo enquanto uma condição for verdadeira..." },
        { title: "Loop for: Iteração sobre Sequências", duration: "19:40", text: "Percorrendo listas e ranges..." },
        { title: "Exercícios e Lógica de Programação", duration: "24:15", text: "Problemas práticos com if/for/while..." }
      ]
    },
    {
      id: "projeto-adivinhacao",
      title: "PROJETO 1: Jogo de Adivinhação Completo",
      author: "Mentor Python",
      category: "Programação",
      type: "curso",
      price: 0.00,
      priceFormatted: "GRÁTIS",
      image: "https://images.unsplash.com/photo-1516321349356-e77cafb83c31?auto=format&fit=crop&w=600&q=80",
      description: "Crie seu primeiro projeto real: um jogo de adivinhação com interface intuitiva, validação de entrada e sistema de pontuação.",
      fullDescription: "Este é seu PRIMEIRO PROJETO REAL! Aqui você vai colocar em prática tudo que aprendeu nos módulos 1 e 2. Você vai criar um jogo completo onde:\n\n✅ O programa pensa em um número 1-100\n✅ Você tenta adivinhar\n✅ O programa dá dicas (maior/menor)\n✅ Conta quantas tentativas você teve\n✅ Você pode jogar novamente ou sair\n\nIncluído:\n- Código comentado passo-a-passo\n- Arquivo Python executável\n- Desafios para evoluir o projeto\n- Solução completa\n\nEste projeto solidifica: variáveis, loops, condicionais, funções, tratamento de erros.",
      rating: 5,
      reviews: 567,
      featured: true,
      tags: ["projeto", "prático", "jogo", "iniciante"],
      chapters: [
        { title: "Entendendo o Desafio", duration: "08:20", text: "Requisitos do projeto e como planejar..." },
        { title: "Estrutura do Código", duration: "15:10", text: "Organizando o projeto em funções..." },
        { title: "Implementação Passo-a-Passo", duration: "28:45", text: "Codificando o jogo linha por linha..." },
        { title: "Testes e Debug", duration: "12:30", text: "Como encontrar e corrigir erros..." },
        { title: "Desafios Extras", duration: "18:20", text: "Melhore seu projeto: dificuldade, histórico, etc..." }
      ]
    },
    {
      id: "python-funcoes",
      title: "Python: Funções e Modularidade",
      author: "Mentor Python",
      category: "Programação",
      type: "audiobook",
      price: 49.90,
      priceFormatted: "R$ 49,90",
      image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=600&q=80",
      description: "Aprenda a criar funções reutilizáveis, parâmetros, retorno de valores e escopo de variáveis.",
      fullDescription: "Funções são o coração da programação bem estruturada. Você vai aprender:\n\n✅ Como definir funções com 'def'\n✅ Parâmetros e argumentos\n✅ Retorno de valores\n✅ Escopo de variáveis (local vs global)\n✅ Boas práticas de nomeação\n✅ Documentação com docstrings\n\nAo final, seu código será profissional, reutilizável e fácil de manter!",
      rating: 5,
      reviews: 256,
      featured: false,
      tags: ["python", "intermediário", "funções", "modularidade"],
      chapters: [
        { title: "Anatomia de uma Função", duration: "16:45", text: "def, parâmetros, return..." },
        { title: "Parâmetros Posicionais e Nomeados", duration: "19:20", text: "Como passar argumentos de diferentes formas..." },
        { title: "Valores de Retorno", duration: "14:50", text: "Retornando um valor, múltiplos valores, None..." },
        { title: "Escopo de Variáveis", duration: "21:30", text: "Local, global, nonlocal. Evitando bugs!" },
        { title: "Documentação com Docstrings", duration: "12:15", text: "Escrevendo código que documenta a si mesmo..." },
        { title: "Projeto Prático: Calculadora Modular", duration: "26:00", text: "Implementando uma calculadora com funções..." }
      ]
    },
    {
      id: "python-estruturas-dados",
      title: "Python: Listas, Dicionários, Tuplas e Sets",
      author: "Mentor Python",
      category: "Programação",
      type: "audiobook",
      price: 59.90,
      priceFormatted: "R$ 59,90",
      image: "https://images.unsplash.com/photo-1633356270529-e4f1e24ebed8?auto=format&fit=crop&w=600&q=80",
      description: "Domine as principais estruturas de dados Python e quando usar cada uma. Essencial para trabalhar com dados.",
      fullDescription: "Estruturas de dados são fundamentais em programação. Você aprenderá:\n\n✅ Listas: criação, manipulação, indexação\n✅ Métodos de lista: append, remove, sort, etc\n✅ Dicionários: chave-valor, quando usar\n✅ Tuplas: imutabilidade e performance\n✅ Sets: operações de conjunto, eliminar duplicatas\n✅ List comprehensions: sintaxe elegante\n\nCom essas ferramentas, você manipulará dados como um profissional!",
      rating: 5,
      reviews: 234,
      featured: false,
      tags: ["python", "intermediário", "estruturas", "dados"],
      chapters: [
        { title: "Listas: Criação e Manipulação", duration: "22:10", text: "Tudo sobre listas em Python..." },
        { title: "Métodos de Lista", duration: "20:45", text: "append, pop, sort, reverse, index, etc..." },
        { title: "Dicionários: Pares Chave-Valor", duration: "21:30", text: "Criando e acessando dicionários..." },
        { title: "Tuplas e Sets", duration: "18:20", text: "Imutabilidade e operações de conjunto..." },
        { title: "List Comprehensions", duration: "16:50", text: "Sintaxe elegante para criar listas..." },
        { title: "Projeto: Gerenciador de Contatos", duration: "28:45", text: "Aplicando estruturas de dados em projeto real..." }
      ]
    },
    {
      id: "projeto-contatos",
      title: "PROJETO 2: Gerenciador de Contatos Completo",
      author: "Mentor Python",
      category: "Programação",
      type: "curso",
      price: 0.00,
      priceFormatted: "GRÁTIS",
      image: "https://images.unsplash.com/photo-1516321349356-e77cafb83c31?auto=format&fit=crop&w=600&q=80",
      description: "Crie um gerenciador de contatos com CRUD completo, validação de dados e busca inteligente.",
      fullDescription: "Seu SEGUNDO PROJETO! Um gerenciador de contatos profissional com:\n\n✅ CRUD: Criar, Ler, Atualizar, Deletar contatos\n✅ Estrutura de dicionários para armazenar dados\n✅ Busca por nome ou telefone\n✅ Menu interativo\n✅ Validação de entrada (telefone, email)\n✅ Listagem formatada\n\nVocê vai aprender:\n- Como estruturar dados com dicionários\n- Validação robusta\n- Interfaces de usuário simples\n- Boas práticas de código\n\nEste projeto solidifica: estruturas de dados, funções, controle de fluxo, validação.",
      rating: 5,
      reviews: 423,
      featured: false,
      tags: ["projeto", "prático", "crud", "intermediário"],
      chapters: [
        { title: "Planejamento do Projeto", duration: "10:15", text: "Requisitos e arquitetura..." },
        { title: "Estrutura de Dados", duration: "16:40", text: "Como organizar os contatos..." },
        { title: "Funções CRUD", duration: "24:20", text: "Criar, ler, atualizar, deletar..." },
        { title: "Validação e Busca", duration: "18:50", text: "Validando telefone e fazendo buscas..." },
        { title: "Menu Interativo", duration: "15:30", text: "Interface amigável para o usuário..." },
        { title: "Testes e Melhorias", duration: "20:00", text: "Debug, edge cases, e melhorias..." }
      ]
    },
    {
      id: "python-erros-arquivos",
      title: "Python: Tratamento de Erros e Manipulação de Arquivos",
      author: "Mentor Python",
      category: "Programação",
      type: "audiobook",
      price: 49.90,
      priceFormatted: "R$ 49,90",
      image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=600&q=80",
      description: "Aprenda try/except para erros robustos e work com arquivos JSON, CSV e texto.",
      fullDescription: "Programas reais precisam de tratamento de erros e persistência de dados. Você vai aprender:\n\n✅ Entendendo exceções\n✅ Try/except: capturando erros\n✅ Finally: limpeza de recursos\n✅ Levantando exceções customizadas\n✅ Leitura de arquivos (open, read, readlines)\n✅ Escrita em arquivos\n✅ JSON: salvando dados estruturados\n✅ CSV: trabalhando com dados tabulares\n\nAgora seus programas serão profissionais e confiáveis!",
      rating: 5,
      reviews: 189,
      featured: false,
      tags: ["python", "intermediário", "erros", "arquivos", "json"],
      chapters: [
        { title: "Entendendo Exceções", duration: "15:20", text: "Tipos de erros e como evitá-los..." },
        { title: "Try/Except em Detalhes", duration: "19:45", text: "Capturando e tratando exceções..." },
        { title: "Finally e Limpeza", duration: "12:30", text: "Garantindo execução de código de limpeza..." },
        { title: "Leitura de Arquivos", duration: "17:10", text: "Abrindo, lendo e fechando arquivos..." },
        { title: "Escrita e JSON", duration: "20:15", text: "Salvando dados em JSON e texto..." },
        { title: "Projeto: TODO App com Persistência", duration: "26:40", text: "App que salva dados entre execuções..." }
      ]
    },
    {
      id: "projeto-todo-app",
      title: "PROJETO 3: TODO App com Salvamento em JSON",
      author: "Mentor Python",
      category: "Programação",
      type: "curso",
      price: 0.00,
      priceFormatted: "GRÁTIS",
      image: "https://images.unsplash.com/photo-1516321349356-e77cafb83c31?auto=format&fit=crop&w=600&q=80",
      description: "Crie um TODO App profissional que salva tarefas em JSON e persiste dados entre execuções.",
      fullDescription: "Seu TERCEIRO PROJETO! Um TODO App que realmente funciona:\n\n✅ Adicionar, remover, listar tarefas\n✅ Marcar como concluída\n✅ Prioridade de tarefas\n✅ Salvar em arquivo JSON\n✅ Carregar ao iniciar\n✅ Tratamento de erros robusto\n✅ Interface limpa e intuitiva\n\nVocê vai aprender:\n- Como estruturar um app com estados\n- Persistência de dados\n- Tratamento de arquivos\n- Boas práticas de UX\n\nEste projeto solidifica: funções, estruturas de dados, arquivos, erros, lógica.",
      rating: 5,
      reviews: 512,
      featured: false,
      tags: ["projeto", "prático", "json", "app", "intermediário"],
      chapters: [
        { title: "Especificação do Projeto", duration: "09:30", text: "O que vamos construir..." },
        { title: "Estrutura de Dados para Tarefas", duration: "14:20", text: "Como representar tarefas..." },
        { title: "Operações CRUD de Tarefas", duration: "22:15", text: "Criar, ler, atualizar, deletar..." },
        { title: "Salvamento em JSON", duration: "18:40", text: "Persistindo dados entre execuções..." },
        { title: "Carregamento e Inicialização", duration: "12:50", text: "Recuperando dados salvos..." },
        { title: "Menu e Interface", duration: "16:25", text: "UX e interação com usuário..." },
        { title: "Testes e Deploy", duration: "20:10", text: "Testando o app e entregando..." }
      ]
    },
    {
      id: "python-poo",
      title: "Python: Programação Orientada a Objetos (POO)",
      author: "Mentor Python",
      category: "Programação",
      type: "audiobook",
      price: 59.90,
      priceFormatted: "R$ 59,90",
      image: "https://images.unsplash.com/photo-1633356270529-e4f1e24ebed8?auto=format&fit=crop&w=600&q=80",
      description: "Domine classes, objetos, herança e polimorfismo. POO é essencial para código profissional.",
      fullDescription: "POO é o padrão industrial de programação. Você vai aprender:\n\n✅ Conceito de classes e objetos\n✅ Atributos e métodos\n✅ Construtor __init__\n✅ Encapsulamento (privado/público)\n✅ Herança: reutilização de código\n✅ Polimorfismo: flexibilidade\n✅ Composição vs Herança\n✅ Métodos mágicos (__str__, __repr__)\n\nCom POO, você escreverá código escalável e profissional!",
      rating: 5,
      reviews: 267,
      featured: false,
      tags: ["python", "avançado", "poo", "classes", "objetos"],
      chapters: [
        { title: "Introdução a Objetos", duration: "18:20", text: "Pensando em termos de objetos..." },
        { title: "Definindo Classes", duration: "20:45", text: "class, def __init__, self..." },
        { title: "Atributos e Métodos", duration: "19:30", text: "Dados e comportamento dos objetos..." },
        { title: "Herança", duration: "22:10", text: "Reutilizando e estendendo classes..." },
        { title: "Polimorfismo e Sobrescrita", duration: "18:50", text: "Comportamentos diferentes para mesma interface..." },
        { title: "Projeto: Sistema de Biblioteca com POO", duration: "32:20", text: "Classes Livro, Usuário, Biblioteca..." }
      ]
    },
    {
      id: "python-apis-dados",
      title: "Python: APIs, Requisições HTTP e Tratamento de Dados",
      author: "Mentor Python",
      category: "Programação",
      type: "audiobook",
      price: 59.90,
      priceFormatted: "R$ 59,90",
      image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=600&q=80",
      description: "Conecte seu código ao mundo real. Aprenda a consumir APIs públicas e processar dados JSON.",
      fullDescription: "APIs são a ponte entre sua aplicação e o mundo. Você vai aprender:\n\n✅ Requisições HTTP com requests\n✅ Status codes e headers\n✅ Parsing JSON\n✅ APIs REST: conceitos fundamentais\n✅ Autenticação básica\n✅ Tratamento de erros de rede\n✅ Rate limiting\n✅ Projetos práticos com APIs públicas\n\nVocê criará aplicações que se conectam ao mundo real!",
      rating: 5,
      reviews: 198,
      featured: false,
      tags: ["python", "avançado", "api", "requisições", "dados"],
      chapters: [
        { title: "HTTP Fundamentos", duration: "16:40", text: "GET, POST, PUT, DELETE..." },
        { title: "Biblioteca Requests", duration: "18:20", text: "Como fazer requisições HTTP..." },
        { title: "Parsing JSON", duration: "14:50", text: "Extraindo dados de respostas..." },
        { title: "Tratamento de Erros", duration: "15:30", text: "Lidando com timeouts e falhas..." },
        { title: "APIs Públicas Reais", duration: "22:15", text: "Consumindo OpenWeather, GitHub, etc..." },
        { title: "Projeto: Dashboard de Dados", duration: "28:40", text: "Reunindo dados de múltiplas APIs..." }
      ]
    },
    {
      id: "python-banco-dados",
      title: "Python: Banco de Dados com SQL e SQLite",
      author: "Mentor Python",
      category: "Programação",
      type: "audiobook",
      price: 59.90,
      priceFormatted: "R$ 59,90",
      image: "https://images.unsplash.com/photo-1633356270529-e4f1e24ebed8?auto=format&fit=crop&w=600&q=80",
      description: "Aprenda SQL, entenda bancos de dados relacionais e integre Python com SQLite/PostgreSQL.",
      fullDescription: "Dados estruturados exigem bancos de dados. Você vai aprender:\n\n✅ Conceitos de bancos relacionais\n✅ SQL: SELECT, INSERT, UPDATE, DELETE\n✅ Tabelas, índices, constraints\n✅ SQLite: banco embutido\n✅ Módulo sqlite3 do Python\n✅ ORM com SQLAlchemy\n✅ Transações e ACID\n✅ Queries complexas com JOINs\n\nAgora seus dados estarão organizados e seguros!",
      rating: 5,
      reviews: 156,
      featured: false,
      tags: ["python", "avançado", "sql", "banco", "dados"],
      chapters: [
        { title: "Conceitos de Bancos de Dados", duration: "17:45", text: "Tabelas, linhas, colunas..." },
        { title: "SQL Básico: CRUD", duration: "21:20", text: "CREATE, READ, UPDATE, DELETE..." },
        { title: "SQLite com Python", duration: "19:30", text: "Conexão, cursor, execução..." },
        { title: "Queries Avançadas", duration: "20:10", text: "JOINs, WHERE, ORDER BY, GROUP BY..." },
        { title: "ORM com SQLAlchemy", duration: "18:50", text: "Mapping de classes a tabelas..." },
        { title: "Projeto: App com Banco de Dados", duration: "30:15", text: "Integração completa Python + SQLite..." }
      ]
    },
    {
      id: "projeto-biblioteca",
      title: "PROJETO 4: Sistema de Biblioteca Completo",
      author: "Mentor Python",
      category: "Programação",
      type: "curso",
      price: 0.00,
      priceFormatted: "GRÁTIS",
      image: "https://images.unsplash.com/photo-1516321349356-e77cafb83c31?auto=format&fit=crop&w=600&q=80",
      description: "Crie um sistema real de gerenciamento de biblioteca com POO, BD, e recursos profissionais.",
      fullDescription: "Seu PROJETO CAPSTONE! Um sistema profissional de biblioteca:\n\n✅ Classes: Livro, Usuário, Biblioteca\n✅ Banco de dados SQLite\n✅ CRUD completo de livros\n✅ Controle de empréstimos/devoluções\n✅ Multa por atraso\n✅ Relatórios e estatísticas\n✅ Busca avançada\n✅ Validação e erros robustos\n\nVocê vai integrar:\n- POO (classes, herança)\n- Banco de dados (SQL, SQLite)\n- Tratamento de erros\n- Estruturas de dados\n- Funções bem organizadas\n\nEste é um projeto REAL que pode ir para seu portfólio!",
      rating: 5,
      reviews: 634,
      featured: false,
      tags: ["projeto", "capstone", "poo", "banco", "avançado"],
      chapters: [
        { title: "Especificação e Design", duration: "12:40", text: "Arquitetura do sistema..." },
        { title: "Modelagem com Banco de Dados", duration: "18:25", text: "Tabelas e relacionamentos..." },
        { title: "Classes em Python", duration: "22:30", text: "Livro, Usuário, Biblioteca..." },
        { title: "CRUD de Livros", duration: "20:15", text: "Criar, ler, atualizar, deletar..." },
        { title: "Sistema de Empréstimos", duration: "24:50", text: "Controle de devolução e multa..." },
        { title: "Relatórios e Buscas", duration: "18:40", text: "Queries complexas e estatísticas..." },
        { title: "Testes Completos", duration: "21:30", text: "Testando tudo o que criamos..." }
      ]
    },
    {
      id: "python-web-flask",
      title: "Python: Web Development com Flask",
      author: "Mentor Python",
      category: "Programação",
      type: "audiobook",
      price: 69.90,
      priceFormatted: "R$ 69,90",
      image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=600&q=80",
      description: "Construa aplicações web do zero com Flask. HTTP, rotas, templates, formulários e mais.",
      fullDescription: "Flask é o framework web mais leve e poderoso. Você vai aprender:\n\n✅ Conceitos de web e HTTP\n✅ Rotas e views\n✅ Templates com Jinja2\n✅ Formulários com WTForms\n✅ Autenticação básica\n✅ Integração com banco de dados\n✅ Deploy em Heroku/PythonAnywhere\n✅ REST APIs com Flask\n\nVocê criará aplicações web profissionais!",
      rating: 5,
      reviews: 223,
      featured: false,
      tags: ["python", "avançado", "web", "flask", "http"],
      chapters: [
        { title: "Conceitos de Web", duration: "15:30", text: "HTTP, requests, responses..." },
        { title: "Hello Flask", duration: "16:45", text: "Seu primeiro servidor web..." },
        { title: "Rotas e Views", duration: "19:20", text: "Mapeando URLs para funções..." },
        { title: "Templates com Jinja2", duration: "20:40", text: "HTML dinâmico com Python..." },
        { title: "Formulários e Validação", duration: "18:55", text: "Recebendo dados do usuário..." },
        { title: "Projeto: Blog Completo com Flask", duration: "34:30", text: "Posts, comentários, autenticação..." }
      ]
    },
    {
      id: "python-testes",
      title: "Python: Testes Unitários e Qualidade de Código",
      author: "Mentor Python",
      category: "Programação",
      type: "audiobook",
      price: 49.90,
      priceFormatted: "R$ 49,90",
      image: "https://images.unsplash.com/photo-1633356270529-e4f1e24ebed8?auto=format&fit=crop&w=600&q=80",
      description: "Escreva código confiável com testes. unittest, pytest, cobertura de testes e boas práticas.",
      fullDescription: "Código profissional é testado! Você vai aprender:\n\n✅ Testes unitários com unittest\n✅ Pytest: framework moderno de testes\n✅ Test-driven development (TDD)\n✅ Cobertura de testes\n✅ Mocks e fixtures\n✅ Integração contínua\n✅ PEP 8 e linting\n✅ Type hints para segurança\n\nSeu código será confiável e profissional!",
      rating: 5,
      reviews: 134,
      featured: false,
      tags: ["python", "avançado", "testes", "qualidade", "pytest"],
      chapters: [
        { title: "Por que Testar", duration: "12:15", text: "Benefícios e boas práticas..." },
        { title: "Testes Unitários com unittest", duration: "19:30", text: "TestCase, assertions, fixtures..." },
        { title: "Pytest Moderno", duration: "17:45", text: "Sintaxe elegante para testes..." },
        { title: "Test-Driven Development", duration: "16:20", text: "Escrevendo testes ANTES do código..." },
        { title: "Mocks e Patches", duration: "15:50", text: "Isolando código para testes..." },
        { title: "Cobertura e CI/CD", duration: "20:40", text: "Medindo qualidade e automatizando..." }
      ]
    },
    {
      id: "projeto-capstone-final",
      title: "PROJETO 5: Capstone - Sistema Web Completo",
      author: "Mentor Python",
      category: "Programação",
      type: "curso",
      price: 0.00,
      priceFormatted: "GRÁTIS",
      image: "https://images.unsplash.com/photo-1516321349356-e77cafb83c31?auto=format&fit=crop&w=600&q=80",
      description: "Seu PROJETO FINAL: uma aplicação web profissional com tudo que aprendeu. Do zero ao deploy!",
      fullDescription: "Este é o projeto FINAL do curso! Uma aplicação web completa e pronta para portfólio:\n\n✅ Backend com Flask\n✅ Frontend com HTML/CSS/JavaScript\n✅ Banco de dados com SQLite\n✅ Autenticação de usuários\n✅ CRUD completo\n✅ Testes unitários\n✅ Tratamento de erros\n✅ Deploy em produção\n✅ Documentação profissional\n\nVocê integrará:\n- Tudo que aprendeu no curso\n- Boas práticas de código\n- Segurança e validação\n- UX/UI funcional\n\nAo final, você terá um projeto REAL para mostrar a empregadores!",
      rating: 5,
      reviews: 789,
      featured: false,
      tags: ["projeto", "capstone", "web", "completo", "avançado"],
      chapters: [
        { title: "Especificação do Projeto", duration: "10:20", text: "O que vamos construir..." },
        { title: "Setup e Arquitetura", duration: "14:30", text: "Estruturando o projeto..." },
        { title: "Backend com Flask", duration: "28:45", text: "Rotas, modelos, lógica..." },
        { title: "Frontend e Templates", duration: "22:15", text: "HTML dinâmico e estilos..." },
        { title: "Autenticação e Segurança", duration: "18:50", text: "Login, senhas, validação..." },
        { title: "Testes Completos", duration: "20:30", text: "Testando backend e frontend..." },
        { title: "Deploy em Produção", duration: "15:25", text: "Publicando seu app online..." },
        { title: "Documentação e Portfólio", duration: "12:40", text: "Preparando para empregadores..." }
      ]
    },
  ],

  // ── TRILHAS ────────────────────────────────────────────────────
  // Adicione trilhas aqui. No campo "productIds", liste os IDs dos
  // produtos que fazem parte da trilha (devem existir acima em products).
  trails: [
    {
      id: "foco-disciplina",
      title: "Foco e Disciplina",
      description: "Desenvolva foco profundo e hábitos de alta performance para conquistar seus objetivos com consistência.",
      category: "Mente",
      level: "Iniciante",
      image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=600&q=80",
      lessons: 12,
      completed: 6,
      productIds: ["produtividade-maxima", "inteligencia-emocional"],
    },
    {
      id: "aprender-ensinar",
      title: "Aprender para Ensinar",
      description: "Como absorver e transmitir conhecimento de forma eficaz e transformadora para qualquer audiência.",
      category: "Educação",
      level: "Intermediário",
      image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=600&q=80",
      lessons: 15,
      completed: 8,
      productIds: ["neurociencia-aprendizado", "inteligencia-emocional"],
    },
    {
      id: "comunicacao-eficaz",
      title: "Comunicação Eficaz",
      description: "Fale com clareza, ouça com presença e construa conexões reais em qualquer contexto profissional ou pessoal.",
      category: "Carreira",
      level: "Iniciante",
      image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=600&q=80",
      lessons: 10,
      completed: 5,
      productIds: ["inteligencia-emocional", "lideranca-criativa"],
    },
    {
      id: "lideranca-gestao",
      title: "Liderança e Gestão",
      description: "Lidere equipes, gerencie projetos e crie culturas de alto desempenho com autenticidade e propósito.",
      category: "Carreira",
      level: "Avançado",
      image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=600&q=80",
      lessons: 14,
      completed: 7,
      productIds: ["lideranca-criativa", "mentalidade-sucesso"],
    },
    {
      id: "saude-mental",
      title: "Saúde Mental e Equilíbrio",
      description: "Ferramentas práticas para gerenciar ansiedade, estresse e bem-estar emocional no cotidiano.",
      category: "Saúde",
      level: "Iniciante",
      image: "https://images.unsplash.com/photo-1531747118685-ca8fa6e08806?auto=format&fit=crop&w=600&q=80",
      lessons: 9,
      completed: 0,
      productIds: ["meditacao-guiada", "meditacao-budista"],
    },
    {
      id: "financas-do-zero",
      title: "Finanças do Zero",
      description: "Da dívida ao patrimônio: aprenda a gerenciar e investir dinheiro com inteligência e consistência.",
      category: "Finanças",
      level: "Iniciante",
      image: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&w=600&q=80",
      lessons: 16,
      completed: 4,
      productIds: ["financas-pessoais"],
    },
    {
      id: "ciencia-sono",
      title: "Ciência do Sono",
      description: "Durma melhor, acorde disposto e maximize seu desempenho cognitivo e físico através do sono de qualidade.",
      category: "Saúde",
      level: "Iniciante",
      image: "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=600&q=80",
      lessons: 8,
      completed: 8,
      productIds: ["neurociencia-aprendizado", "meditacao-guiada"],
    },
    {
      id: "criatividade-inovacao",
      title: "Criatividade e Inovação",
      description: "Técnicas de pensamento criativo para resolver problemas complexos e criar soluções únicas e impactantes.",
      category: "Criatividade",
      level: "Intermediário",
      image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=600&q=80",
      lessons: 11,
      completed: 3,
      productIds: ["arte-digital", "mentalidade-sucesso"],
    },
    {
      id: "estoicismo",
      title: "Estoicismo Prático",
      description: "Filosofia aplicada ao dia a dia: resiliência, foco e serenidade em qualquer situação da vida moderna.",
      category: "Filosofia",
      level: "Intermediário",
      image: "https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=600&q=80",
      lessons: 10,
      completed: 0,
      productIds: ["meditacao-budista"],
    },
    {
      id: "python-zero-avancado",
      title: "Python: Do Zero ao Avançado",
      description: "Jornada completa de programação. 10 módulos + 5 projetos reais. Metodologia Project-Based Learning. Saia criando aplicações profissionais!",
      category: "Programação",
      level: "Iniciante",
      image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=600&q=80",
      lessons: 50,
      completed: 0,
      productIds: [
        "python-fundamentos",
        "python-controle-fluxo",
        "projeto-adivinhacao",
        "python-funcoes",
        "python-estruturas-dados",
        "projeto-contatos",
        "python-erros-arquivos",
        "projeto-todo-app",
        "python-poo",
        "python-apis-dados",
        "python-banco-dados",
        "projeto-biblioteca",
        "python-web-flask",
        "python-testes",
        "projeto-capstone-final"
      ]
    },
  ],

}; // fim window.HB.content
